apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations: {}
  name: claudia-api-override
  namespace: claudia-api
proxy:
  connect_timeout: 600000
  protocol: http
  read_timeout: 600000
  write_timeout: 600000
