
CREATE USER supabase_auth_admin WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE USER supabase_storage_admin WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE USER supabase_admin WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE USER supabase_functions_admin WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE USER authenticator WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE USER anon WITH PASSWORD 'f0c14f5d31f63b5c243478cd81d77ef7deced59307cd399d80d21a538a0b5d3c';
CREATE ROLE authenticated;
CREATE ROLE service_role;


GRANT ALL PRIVILEGES ON DATABASE postgres TO supabase_admin;
GRANT ALL PRIVILEGES ON DATABASE postgres TO supabase_storage_admin;
GRANT ALL PRIVILEGES ON DATABASE postgres TO supabase_auth_admin;
GRANT ALL PRIVILEGES ON SCHEMA auth TO supabase_auth_admin;
GRANT ALL PRIVILEGES ON SCHEMA auth TO supabase_storage_admin;
GRANT ALL PRIVILEGES ON SCHEMA auth TO supabase_admin;


CREATE SCHEMA IF NOT EXISTS auth AUTHORIZATION supabase_auth_admin;
CREATE SCHEMA IF NOT EXISTS storage AUTHORIZATION supabase_storage_admin;
CREATE SCHEMA IF NOT EXISTS realtime;
CREATE SCHEMA IF NOT EXISTS _realtime;


GRANT USAGE ON SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO authenticator;
GRANT USAGE ON SCHEMA auth TO authenticator;
GRANT USAGE ON SCHEMA storage TO authenticator;


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO supabase_auth_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO supabase_auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO supabase_auth_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO supabase_auth_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA storage TO supabase_storage_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA storage TO supabase_storage_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON TABLES TO supabase_storage_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA storage GRANT ALL ON SEQUENCES TO supabase_storage_admin;


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO supabase_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA auth TO supabase_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO supabase_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO supabase_admin;