apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  annotations: {}
  labels:
    app: generative-ids-api
    enviroment: prd
  name: generative-ids-api-override
  namespace: generative-ids-api
proxy:
  connect_timeout: 1200000
  protocol: http
  read_timeout: 1200000
  write_timeout: 1200000
